name: circle_bottom_navigation_bar
description: An animated, beauty and functional Bottom Navigation Bar you app.
version: 0.3.0
homepage: https://github.com/pzentenoe/circle_bottom_navigation_bar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  analyzer: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
